// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contributor.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createContributor = `-- name: CreateContributor :one
INSERT INTO contributor (id, short_id, site_id, profile_id, handle, name, surname, bio, social_links, role, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, short_id, site_id, profile_id, handle, name, surname, bio, social_links, role, created_by, updated_by, created_at, updated_at
`

type CreateContributorParams struct {
	ID          string         `json:"id"`
	ShortID     string         `json:"short_id"`
	SiteID      string         `json:"site_id"`
	ProfileID   sql.NullString `json:"profile_id"`
	Handle      string         `json:"handle"`
	Name        string         `json:"name"`
	Surname     string         `json:"surname"`
	Bio         string         `json:"bio"`
	SocialLinks string         `json:"social_links"`
	Role        string         `json:"role"`
	CreatedBy   string         `json:"created_by"`
	UpdatedBy   string         `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateContributor(ctx context.Context, arg CreateContributorParams) (Contributor, error) {
	row := q.db.QueryRowContext(ctx, createContributor,
		arg.ID,
		arg.ShortID,
		arg.SiteID,
		arg.ProfileID,
		arg.Handle,
		arg.Name,
		arg.Surname,
		arg.Bio,
		arg.SocialLinks,
		arg.Role,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Contributor
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.SiteID,
		&i.ProfileID,
		&i.Handle,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContributor = `-- name: DeleteContributor :exec
DELETE FROM contributor WHERE id = ?
`

func (q *Queries) DeleteContributor(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContributor, id)
	return err
}

const getContributor = `-- name: GetContributor :one
SELECT id, short_id, site_id, profile_id, handle, name, surname, bio, social_links, role, created_by, updated_by, created_at, updated_at FROM contributor WHERE id = ?
`

func (q *Queries) GetContributor(ctx context.Context, id string) (Contributor, error) {
	row := q.db.QueryRowContext(ctx, getContributor, id)
	var i Contributor
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.SiteID,
		&i.ProfileID,
		&i.Handle,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributorByHandle = `-- name: GetContributorByHandle :one
SELECT id, short_id, site_id, profile_id, handle, name, surname, bio, social_links, role, created_by, updated_by, created_at, updated_at FROM contributor WHERE site_id = ? AND handle = ?
`

type GetContributorByHandleParams struct {
	SiteID string `json:"site_id"`
	Handle string `json:"handle"`
}

func (q *Queries) GetContributorByHandle(ctx context.Context, arg GetContributorByHandleParams) (Contributor, error) {
	row := q.db.QueryRowContext(ctx, getContributorByHandle, arg.SiteID, arg.Handle)
	var i Contributor
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.SiteID,
		&i.ProfileID,
		&i.Handle,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributorsBySiteID = `-- name: ListContributorsBySiteID :many
SELECT id, short_id, site_id, profile_id, handle, name, surname, bio, social_links, role, created_by, updated_by, created_at, updated_at FROM contributor WHERE site_id = ? ORDER BY name, surname
`

func (q *Queries) ListContributorsBySiteID(ctx context.Context, siteID string) ([]Contributor, error) {
	rows, err := q.db.QueryContext(ctx, listContributorsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contributor
	for rows.Next() {
		var i Contributor
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.SiteID,
			&i.ProfileID,
			&i.Handle,
			&i.Name,
			&i.Surname,
			&i.Bio,
			&i.SocialLinks,
			&i.Role,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributorsWithProfile = `-- name: ListContributorsWithProfile :many
SELECT c.id, c.short_id, c.site_id, c.profile_id, c.handle, c.name, c.surname, c.bio, c.social_links, c.role, c.created_by, c.updated_by, c.created_at, c.updated_at, p.photo_path as profile_photo_path
FROM contributor c
LEFT JOIN profile p ON c.profile_id = p.id
WHERE c.site_id = ?
ORDER BY c.name, c.surname
`

type ListContributorsWithProfileRow struct {
	ID               string         `json:"id"`
	ShortID          string         `json:"short_id"`
	SiteID           string         `json:"site_id"`
	ProfileID        sql.NullString `json:"profile_id"`
	Handle           string         `json:"handle"`
	Name             string         `json:"name"`
	Surname          string         `json:"surname"`
	Bio              string         `json:"bio"`
	SocialLinks      string         `json:"social_links"`
	Role             string         `json:"role"`
	CreatedBy        string         `json:"created_by"`
	UpdatedBy        string         `json:"updated_by"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ProfilePhotoPath sql.NullString `json:"profile_photo_path"`
}

func (q *Queries) ListContributorsWithProfile(ctx context.Context, siteID string) ([]ListContributorsWithProfileRow, error) {
	rows, err := q.db.QueryContext(ctx, listContributorsWithProfile, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContributorsWithProfileRow
	for rows.Next() {
		var i ListContributorsWithProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.SiteID,
			&i.ProfileID,
			&i.Handle,
			&i.Name,
			&i.Surname,
			&i.Bio,
			&i.SocialLinks,
			&i.Role,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfilePhotoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContributorProfile = `-- name: SetContributorProfile :exec
UPDATE contributor SET profile_id = ?, updated_by = ?, updated_at = ? WHERE id = ?
`

type SetContributorProfileParams struct {
	ProfileID sql.NullString `json:"profile_id"`
	UpdatedBy string         `json:"updated_by"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) SetContributorProfile(ctx context.Context, arg SetContributorProfileParams) error {
	_, err := q.db.ExecContext(ctx, setContributorProfile,
		arg.ProfileID,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateContributor = `-- name: UpdateContributor :one
UPDATE contributor SET
    handle = ?,
    name = ?,
    surname = ?,
    bio = ?,
    social_links = ?,
    role = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, short_id, site_id, profile_id, handle, name, surname, bio, social_links, role, created_by, updated_by, created_at, updated_at
`

type UpdateContributorParams struct {
	Handle      string    `json:"handle"`
	Name        string    `json:"name"`
	Surname     string    `json:"surname"`
	Bio         string    `json:"bio"`
	SocialLinks string    `json:"social_links"`
	Role        string    `json:"role"`
	UpdatedBy   string    `json:"updated_by"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateContributor(ctx context.Context, arg UpdateContributorParams) (Contributor, error) {
	row := q.db.QueryRowContext(ctx, updateContributor,
		arg.Handle,
		arg.Name,
		arg.Surname,
		arg.Bio,
		arg.SocialLinks,
		arg.Role,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Contributor
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.SiteID,
		&i.ProfileID,
		&i.Handle,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
