// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countContent = `-- name: CountContent :one
SELECT COUNT(*) FROM content WHERE site_id = ?
`

func (q *Queries) CountContent(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContent, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchContent = `-- name: CountSearchContent :one
SELECT COUNT(*) FROM content WHERE site_id = ? AND heading LIKE ?
`

type CountSearchContentParams struct {
	SiteID  string `json:"site_id"`
	Heading string `json:"heading"`
}

func (q *Queries) CountSearchContent(ctx context.Context, arg CountSearchContentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchContent, arg.SiteID, arg.Heading)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContent = `-- name: CreateContent :one
INSERT INTO content (id, site_id, user_id, short_id, section_id, contributor_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id
`

type CreateContentParams struct {
	ID            string         `json:"id"`
	SiteID        string         `json:"site_id"`
	UserID        sql.NullString `json:"user_id"`
	ShortID       sql.NullString `json:"short_id"`
	SectionID     sql.NullString `json:"section_id"`
	ContributorID sql.NullString `json:"contributor_id"`
	Kind          sql.NullString `json:"kind"`
	Heading       string         `json:"heading"`
	Summary       sql.NullString `json:"summary"`
	Body          sql.NullString `json:"body"`
	Draft         sql.NullInt64  `json:"draft"`
	Featured      sql.NullInt64  `json:"featured"`
	Series        sql.NullString `json:"series"`
	SeriesOrder   sql.NullInt64  `json:"series_order"`
	PublishedAt   sql.NullTime   `json:"published_at"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, createContent,
		arg.ID,
		arg.SiteID,
		arg.UserID,
		arg.ShortID,
		arg.SectionID,
		arg.ContributorID,
		arg.Kind,
		arg.Heading,
		arg.Summary,
		arg.Body,
		arg.Draft,
		arg.Featured,
		arg.Series,
		arg.SeriesOrder,
		arg.PublishedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.ShortID,
		&i.SectionID,
		&i.Kind,
		&i.Heading,
		&i.Summary,
		&i.Body,
		&i.Draft,
		&i.Featured,
		&i.Series,
		&i.SeriesOrder,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContributorID,
	)
	return i, err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM content WHERE id = ?
`

func (q *Queries) DeleteContent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContent, id)
	return err
}

const getAllContentWithMeta = `-- name: GetAllContentWithMeta :many
SELECT
    c.id, c.site_id, c.user_id, c.short_id, c.section_id, c.kind, c.heading, c.summary, c.body, c.draft, c.featured, c.series, c.series_order, c.published_at, c.created_by, c.updated_by, c.created_at, c.updated_at, c.contributor_id,
    s.path as section_path,
    s.name as section_name,
    m.summary as meta_summary,
    m.description as meta_description,
    m.keywords as meta_keywords
FROM content c
LEFT JOIN section s ON c.section_id = s.id
LEFT JOIN meta m ON c.id = m.content_id
WHERE c.site_id = ?
ORDER BY c.created_at DESC
`

type GetAllContentWithMetaRow struct {
	ID              string         `json:"id"`
	SiteID          string         `json:"site_id"`
	UserID          sql.NullString `json:"user_id"`
	ShortID         sql.NullString `json:"short_id"`
	SectionID       sql.NullString `json:"section_id"`
	Kind            sql.NullString `json:"kind"`
	Heading         string         `json:"heading"`
	Summary         sql.NullString `json:"summary"`
	Body            sql.NullString `json:"body"`
	Draft           sql.NullInt64  `json:"draft"`
	Featured        sql.NullInt64  `json:"featured"`
	Series          sql.NullString `json:"series"`
	SeriesOrder     sql.NullInt64  `json:"series_order"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	ContributorID   sql.NullString `json:"contributor_id"`
	SectionPath     sql.NullString `json:"section_path"`
	SectionName     sql.NullString `json:"section_name"`
	MetaSummary     sql.NullString `json:"meta_summary"`
	MetaDescription sql.NullString `json:"meta_description"`
	MetaKeywords    sql.NullString `json:"meta_keywords"`
}

func (q *Queries) GetAllContentWithMeta(ctx context.Context, siteID string) ([]GetAllContentWithMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllContentWithMeta, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContentWithMetaRow
	for rows.Next() {
		var i GetAllContentWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.ShortID,
			&i.SectionID,
			&i.Kind,
			&i.Heading,
			&i.Summary,
			&i.Body,
			&i.Draft,
			&i.Featured,
			&i.Series,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContributorID,
			&i.SectionPath,
			&i.SectionName,
			&i.MetaSummary,
			&i.MetaDescription,
			&i.MetaKeywords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContent = `-- name: GetContent :one
SELECT id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id FROM content WHERE id = ?
`

func (q *Queries) GetContent(ctx context.Context, id string) (Content, error) {
	row := q.db.QueryRowContext(ctx, getContent, id)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.ShortID,
		&i.SectionID,
		&i.Kind,
		&i.Heading,
		&i.Summary,
		&i.Body,
		&i.Draft,
		&i.Featured,
		&i.Series,
		&i.SeriesOrder,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContributorID,
	)
	return i, err
}

const getContentBySectionID = `-- name: GetContentBySectionID :many
SELECT id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id FROM content WHERE section_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetContentBySectionID(ctx context.Context, sectionID sql.NullString) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, getContentBySectionID, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.ShortID,
			&i.SectionID,
			&i.Kind,
			&i.Heading,
			&i.Summary,
			&i.Body,
			&i.Draft,
			&i.Featured,
			&i.Series,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContributorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentBySiteID = `-- name: GetContentBySiteID :many
SELECT id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id FROM content WHERE site_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetContentBySiteID(ctx context.Context, siteID string) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, getContentBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.ShortID,
			&i.SectionID,
			&i.Kind,
			&i.Heading,
			&i.Summary,
			&i.Body,
			&i.Draft,
			&i.Featured,
			&i.Series,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContributorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentWithMeta = `-- name: GetContentWithMeta :one
SELECT
    c.id, c.site_id, c.user_id, c.short_id, c.section_id, c.kind, c.heading, c.summary, c.body, c.draft, c.featured, c.series, c.series_order, c.published_at, c.created_by, c.updated_by, c.created_at, c.updated_at, c.contributor_id,
    s.path as section_path,
    s.name as section_name,
    m.summary as meta_summary,
    m.description as meta_description,
    m.keywords as meta_keywords
FROM content c
LEFT JOIN section s ON c.section_id = s.id
LEFT JOIN meta m ON c.id = m.content_id
WHERE c.id = ?
`

type GetContentWithMetaRow struct {
	ID              string         `json:"id"`
	SiteID          string         `json:"site_id"`
	UserID          sql.NullString `json:"user_id"`
	ShortID         sql.NullString `json:"short_id"`
	SectionID       sql.NullString `json:"section_id"`
	Kind            sql.NullString `json:"kind"`
	Heading         string         `json:"heading"`
	Summary         sql.NullString `json:"summary"`
	Body            sql.NullString `json:"body"`
	Draft           sql.NullInt64  `json:"draft"`
	Featured        sql.NullInt64  `json:"featured"`
	Series          sql.NullString `json:"series"`
	SeriesOrder     sql.NullInt64  `json:"series_order"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	ContributorID   sql.NullString `json:"contributor_id"`
	SectionPath     sql.NullString `json:"section_path"`
	SectionName     sql.NullString `json:"section_name"`
	MetaSummary     sql.NullString `json:"meta_summary"`
	MetaDescription sql.NullString `json:"meta_description"`
	MetaKeywords    sql.NullString `json:"meta_keywords"`
}

func (q *Queries) GetContentWithMeta(ctx context.Context, id string) (GetContentWithMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getContentWithMeta, id)
	var i GetContentWithMetaRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.ShortID,
		&i.SectionID,
		&i.Kind,
		&i.Heading,
		&i.Summary,
		&i.Body,
		&i.Draft,
		&i.Featured,
		&i.Series,
		&i.SeriesOrder,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContributorID,
		&i.SectionPath,
		&i.SectionName,
		&i.MetaSummary,
		&i.MetaDescription,
		&i.MetaKeywords,
	)
	return i, err
}

const getContentWithPagination = `-- name: GetContentWithPagination :many
SELECT id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id FROM content
WHERE site_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetContentWithPaginationParams struct {
	SiteID string `json:"site_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) GetContentWithPagination(ctx context.Context, arg GetContentWithPaginationParams) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, getContentWithPagination, arg.SiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.ShortID,
			&i.SectionID,
			&i.Kind,
			&i.Heading,
			&i.Summary,
			&i.Body,
			&i.Draft,
			&i.Featured,
			&i.Series,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContributorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedContentBySiteID = `-- name: GetPublishedContentBySiteID :many
SELECT id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id FROM content WHERE site_id = ? AND draft = 0 ORDER BY published_at DESC
`

func (q *Queries) GetPublishedContentBySiteID(ctx context.Context, siteID string) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, getPublishedContentBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.ShortID,
			&i.SectionID,
			&i.Kind,
			&i.Heading,
			&i.Summary,
			&i.Body,
			&i.Draft,
			&i.Featured,
			&i.Series,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContributorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContent = `-- name: SearchContent :many
SELECT id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id FROM content
WHERE site_id = ? AND heading LIKE ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchContentParams struct {
	SiteID  string `json:"site_id"`
	Heading string `json:"heading"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) SearchContent(ctx context.Context, arg SearchContentParams) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, searchContent,
		arg.SiteID,
		arg.Heading,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.ShortID,
			&i.SectionID,
			&i.Kind,
			&i.Heading,
			&i.Summary,
			&i.Body,
			&i.Draft,
			&i.Featured,
			&i.Series,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContributorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContent = `-- name: UpdateContent :one
UPDATE content SET
    section_id = ?,
    contributor_id = ?,
    kind = ?,
    heading = ?,
    summary = ?,
    body = ?,
    draft = ?,
    featured = ?,
    series = ?,
    series_order = ?,
    published_at = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, user_id, short_id, section_id, kind, heading, summary, body, draft, featured, series, series_order, published_at, created_by, updated_by, created_at, updated_at, contributor_id
`

type UpdateContentParams struct {
	SectionID     sql.NullString `json:"section_id"`
	ContributorID sql.NullString `json:"contributor_id"`
	Kind          sql.NullString `json:"kind"`
	Heading       string         `json:"heading"`
	Summary       sql.NullString `json:"summary"`
	Body          sql.NullString `json:"body"`
	Draft         sql.NullInt64  `json:"draft"`
	Featured      sql.NullInt64  `json:"featured"`
	Series        sql.NullString `json:"series"`
	SeriesOrder   sql.NullInt64  `json:"series_order"`
	PublishedAt   sql.NullTime   `json:"published_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, updateContent,
		arg.SectionID,
		arg.ContributorID,
		arg.Kind,
		arg.Heading,
		arg.Summary,
		arg.Body,
		arg.Draft,
		arg.Featured,
		arg.Series,
		arg.SeriesOrder,
		arg.PublishedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.ShortID,
		&i.SectionID,
		&i.Kind,
		&i.Heading,
		&i.Summary,
		&i.Body,
		&i.Draft,
		&i.Featured,
		&i.Series,
		&i.SeriesOrder,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContributorID,
	)
	return i, err
}
