// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: form_submission.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUnreadFormSubmissions = `-- name: CountUnreadFormSubmissions :one
SELECT COUNT(*) FROM form_submission WHERE site_id = ? AND read_at IS NULL
`

func (q *Queries) CountUnreadFormSubmissions(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadFormSubmissions, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFormSubmission = `-- name: CreateFormSubmission :one
INSERT INTO form_submission (id, site_id, form_type, name, email, message, ip_address, user_agent, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, form_type, name, email, message, ip_address, user_agent, read_at, created_at
`

type CreateFormSubmissionParams struct {
	ID        string         `json:"id"`
	SiteID    string         `json:"site_id"`
	FormType  string         `json:"form_type"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Message   string         `json:"message"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (FormSubmission, error) {
	row := q.db.QueryRowContext(ctx, createFormSubmission,
		arg.ID,
		arg.SiteID,
		arg.FormType,
		arg.Name,
		arg.Email,
		arg.Message,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
	)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.FormType,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.IpAddress,
		&i.UserAgent,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFormSubmission = `-- name: DeleteFormSubmission :exec
DELETE FROM form_submission WHERE id = ?
`

func (q *Queries) DeleteFormSubmission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFormSubmission, id)
	return err
}

const getFormSubmission = `-- name: GetFormSubmission :one
SELECT id, site_id, form_type, name, email, message, ip_address, user_agent, read_at, created_at FROM form_submission WHERE id = ?
`

func (q *Queries) GetFormSubmission(ctx context.Context, id string) (FormSubmission, error) {
	row := q.db.QueryRowContext(ctx, getFormSubmission, id)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.FormType,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.IpAddress,
		&i.UserAgent,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFormSubmissionsBySite = `-- name: ListFormSubmissionsBySite :many
SELECT id, site_id, form_type, name, email, message, ip_address, user_agent, read_at, created_at FROM form_submission WHERE site_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListFormSubmissionsBySite(ctx context.Context, siteID string) ([]FormSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listFormSubmissionsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormSubmission
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.FormType,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.IpAddress,
			&i.UserAgent,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFormSubmissionRead = `-- name: MarkFormSubmissionRead :exec
UPDATE form_submission SET read_at = ? WHERE id = ?
`

type MarkFormSubmissionReadParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	ID     string       `json:"id"`
}

func (q *Queries) MarkFormSubmissionRead(ctx context.Context, arg MarkFormSubmissionReadParams) error {
	_, err := q.db.ExecContext(ctx, markFormSubmissionRead, arg.ReadAt, arg.ID)
	return err
}
