// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createContentImage = `-- name: CreateContentImage :exec
INSERT INTO content_images (id, content_id, image_id, is_header, is_featured, order_num, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateContentImageParams struct {
	ID         string        `json:"id"`
	ContentID  string        `json:"content_id"`
	ImageID    string        `json:"image_id"`
	IsHeader   sql.NullInt64 `json:"is_header"`
	IsFeatured sql.NullInt64 `json:"is_featured"`
	OrderNum   sql.NullInt64 `json:"order_num"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

func (q *Queries) CreateContentImage(ctx context.Context, arg CreateContentImageParams) error {
	_, err := q.db.ExecContext(ctx, createContentImage,
		arg.ID,
		arg.ContentID,
		arg.ImageID,
		arg.IsHeader,
		arg.IsFeatured,
		arg.OrderNum,
		arg.CreatedAt,
	)
	return err
}

const createImage = `-- name: CreateImage :one
INSERT INTO image (id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at
`

type CreateImageParams struct {
	ID        string         `json:"id"`
	SiteID    string         `json:"site_id"`
	ShortID   sql.NullString `json:"short_id"`
	FileName  string         `json:"file_name"`
	FilePath  string         `json:"file_path"`
	AltText   sql.NullString `json:"alt_text"`
	Title     sql.NullString `json:"title"`
	Width     sql.NullInt64  `json:"width"`
	Height    sql.NullInt64  `json:"height"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.FileName,
		arg.FilePath,
		arg.AltText,
		arg.Title,
		arg.Width,
		arg.Height,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.FileName,
		&i.FilePath,
		&i.AltText,
		&i.Title,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImageVariant = `-- name: CreateImageVariant :one
INSERT INTO image_variant (id, short_id, image_id, kind, blob_ref, width, height, filesize_bytes, mime, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, short_id, image_id, kind, blob_ref, width, height, filesize_bytes, mime, created_by, updated_by, created_at, updated_at
`

type CreateImageVariantParams struct {
	ID            string         `json:"id"`
	ShortID       string         `json:"short_id"`
	ImageID       string         `json:"image_id"`
	Kind          string         `json:"kind"`
	BlobRef       string         `json:"blob_ref"`
	Width         sql.NullInt64  `json:"width"`
	Height        sql.NullInt64  `json:"height"`
	FilesizeBytes sql.NullInt64  `json:"filesize_bytes"`
	Mime          sql.NullString `json:"mime"`
	CreatedBy     string         `json:"created_by"`
	UpdatedBy     string         `json:"updated_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateImageVariant(ctx context.Context, arg CreateImageVariantParams) (ImageVariant, error) {
	row := q.db.QueryRowContext(ctx, createImageVariant,
		arg.ID,
		arg.ShortID,
		arg.ImageID,
		arg.Kind,
		arg.BlobRef,
		arg.Width,
		arg.Height,
		arg.FilesizeBytes,
		arg.Mime,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ImageVariant
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.ImageID,
		&i.Kind,
		&i.BlobRef,
		&i.Width,
		&i.Height,
		&i.FilesizeBytes,
		&i.Mime,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSectionImage = `-- name: CreateSectionImage :exec
INSERT INTO section_images (id, section_id, image_id, is_header, is_featured, order_num, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSectionImageParams struct {
	ID         string        `json:"id"`
	SectionID  string        `json:"section_id"`
	ImageID    string        `json:"image_id"`
	IsHeader   sql.NullInt64 `json:"is_header"`
	IsFeatured sql.NullInt64 `json:"is_featured"`
	OrderNum   sql.NullInt64 `json:"order_num"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

func (q *Queries) CreateSectionImage(ctx context.Context, arg CreateSectionImageParams) error {
	_, err := q.db.ExecContext(ctx, createSectionImage,
		arg.ID,
		arg.SectionID,
		arg.ImageID,
		arg.IsHeader,
		arg.IsFeatured,
		arg.OrderNum,
		arg.CreatedAt,
	)
	return err
}

const deleteContentImage = `-- name: DeleteContentImage :exec
DELETE FROM content_images WHERE id = ?
`

func (q *Queries) DeleteContentImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContentImage, id)
	return err
}

const deleteContentImageByContentAndImage = `-- name: DeleteContentImageByContentAndImage :exec
DELETE FROM content_images WHERE content_id = ? AND image_id = ?
`

type DeleteContentImageByContentAndImageParams struct {
	ContentID string `json:"content_id"`
	ImageID   string `json:"image_id"`
}

func (q *Queries) DeleteContentImageByContentAndImage(ctx context.Context, arg DeleteContentImageByContentAndImageParams) error {
	_, err := q.db.ExecContext(ctx, deleteContentImageByContentAndImage, arg.ContentID, arg.ImageID)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM image WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteImageVariant = `-- name: DeleteImageVariant :exec
DELETE FROM image_variant WHERE id = ?
`

func (q *Queries) DeleteImageVariant(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImageVariant, id)
	return err
}

const deleteSectionImage = `-- name: DeleteSectionImage :exec
DELETE FROM section_images WHERE id = ?
`

func (q *Queries) DeleteSectionImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSectionImage, id)
	return err
}

const getContentImageWithDetails = `-- name: GetContentImageWithDetails :one
SELECT
    ci.id as content_image_id,
    ci.content_id,
    ci.image_id,
    ci.is_header,
    i.id,
    i.site_id,
    i.file_path
FROM content_images ci
JOIN image i ON ci.image_id = i.id
WHERE ci.id = ?
`

type GetContentImageWithDetailsRow struct {
	ContentImageID string        `json:"content_image_id"`
	ContentID      string        `json:"content_id"`
	ImageID        string        `json:"image_id"`
	IsHeader       sql.NullInt64 `json:"is_header"`
	ID             string        `json:"id"`
	SiteID         string        `json:"site_id"`
	FilePath       string        `json:"file_path"`
}

func (q *Queries) GetContentImageWithDetails(ctx context.Context, id string) (GetContentImageWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getContentImageWithDetails, id)
	var i GetContentImageWithDetailsRow
	err := row.Scan(
		&i.ContentImageID,
		&i.ContentID,
		&i.ImageID,
		&i.IsHeader,
		&i.ID,
		&i.SiteID,
		&i.FilePath,
	)
	return i, err
}

const getContentImagesByContentID = `-- name: GetContentImagesByContentID :many
SELECT id, content_id, image_id, is_header, is_featured, order_num, created_at FROM content_images WHERE content_id = ? ORDER BY order_num
`

func (q *Queries) GetContentImagesByContentID(ctx context.Context, contentID string) ([]ContentImage, error) {
	rows, err := q.db.QueryContext(ctx, getContentImagesByContentID, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentImage
	for rows.Next() {
		var i ContentImage
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.ImageID,
			&i.IsHeader,
			&i.IsFeatured,
			&i.OrderNum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentImagesWithDetails = `-- name: GetContentImagesWithDetails :many
SELECT
    ci.id as content_image_id,
    ci.content_id,
    ci.is_header,
    ci.is_featured,
    ci.order_num,
    i.id,
    i.site_id,
    i.short_id,
    i.file_name,
    i.file_path,
    i.alt_text,
    i.title,
    i.width,
    i.height,
    i.created_at,
    i.updated_at
FROM content_images ci
JOIN image i ON ci.image_id = i.id
WHERE ci.content_id = ?
ORDER BY ci.is_header DESC, ci.order_num
`

type GetContentImagesWithDetailsRow struct {
	ContentImageID string         `json:"content_image_id"`
	ContentID      string         `json:"content_id"`
	IsHeader       sql.NullInt64  `json:"is_header"`
	IsFeatured     sql.NullInt64  `json:"is_featured"`
	OrderNum       sql.NullInt64  `json:"order_num"`
	ID             string         `json:"id"`
	SiteID         string         `json:"site_id"`
	ShortID        sql.NullString `json:"short_id"`
	FileName       string         `json:"file_name"`
	FilePath       string         `json:"file_path"`
	AltText        sql.NullString `json:"alt_text"`
	Title          sql.NullString `json:"title"`
	Width          sql.NullInt64  `json:"width"`
	Height         sql.NullInt64  `json:"height"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetContentImagesWithDetails(ctx context.Context, contentID string) ([]GetContentImagesWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getContentImagesWithDetails, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContentImagesWithDetailsRow
	for rows.Next() {
		var i GetContentImagesWithDetailsRow
		if err := rows.Scan(
			&i.ContentImageID,
			&i.ContentID,
			&i.IsHeader,
			&i.IsFeatured,
			&i.OrderNum,
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.FileName,
			&i.FilePath,
			&i.AltText,
			&i.Title,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImage = `-- name: GetImage :one
SELECT id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at FROM image WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.FileName,
		&i.FilePath,
		&i.AltText,
		&i.Title,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageByPath = `-- name: GetImageByPath :one
SELECT id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at FROM image WHERE site_id = ? AND file_path = ?
`

type GetImageByPathParams struct {
	SiteID   string `json:"site_id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetImageByPath(ctx context.Context, arg GetImageByPathParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByPath, arg.SiteID, arg.FilePath)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.FileName,
		&i.FilePath,
		&i.AltText,
		&i.Title,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageByShortID = `-- name: GetImageByShortID :one
SELECT id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at FROM image WHERE short_id = ?
`

func (q *Queries) GetImageByShortID(ctx context.Context, shortID sql.NullString) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByShortID, shortID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.FileName,
		&i.FilePath,
		&i.AltText,
		&i.Title,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageVariant = `-- name: GetImageVariant :one
SELECT id, short_id, image_id, kind, blob_ref, width, height, filesize_bytes, mime, created_by, updated_by, created_at, updated_at FROM image_variant WHERE id = ?
`

func (q *Queries) GetImageVariant(ctx context.Context, id string) (ImageVariant, error) {
	row := q.db.QueryRowContext(ctx, getImageVariant, id)
	var i ImageVariant
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.ImageID,
		&i.Kind,
		&i.BlobRef,
		&i.Width,
		&i.Height,
		&i.FilesizeBytes,
		&i.Mime,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageVariantsByImageID = `-- name: GetImageVariantsByImageID :many
SELECT id, short_id, image_id, kind, blob_ref, width, height, filesize_bytes, mime, created_by, updated_by, created_at, updated_at FROM image_variant WHERE image_id = ? ORDER BY kind
`

func (q *Queries) GetImageVariantsByImageID(ctx context.Context, imageID string) ([]ImageVariant, error) {
	rows, err := q.db.QueryContext(ctx, getImageVariantsByImageID, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageVariant
	for rows.Next() {
		var i ImageVariant
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.ImageID,
			&i.Kind,
			&i.BlobRef,
			&i.Width,
			&i.Height,
			&i.FilesizeBytes,
			&i.Mime,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesBySiteID = `-- name: GetImagesBySiteID :many
SELECT id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at FROM image WHERE site_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetImagesBySiteID(ctx context.Context, siteID string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImagesBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.FileName,
			&i.FilePath,
			&i.AltText,
			&i.Title,
			&i.Width,
			&i.Height,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionImageWithDetails = `-- name: GetSectionImageWithDetails :one
SELECT
    si.id as section_image_id,
    si.section_id,
    si.image_id,
    si.is_header,
    i.id,
    i.site_id,
    i.file_path
FROM section_images si
JOIN image i ON si.image_id = i.id
WHERE si.id = ?
`

type GetSectionImageWithDetailsRow struct {
	SectionImageID string        `json:"section_image_id"`
	SectionID      string        `json:"section_id"`
	ImageID        string        `json:"image_id"`
	IsHeader       sql.NullInt64 `json:"is_header"`
	ID             string        `json:"id"`
	SiteID         string        `json:"site_id"`
	FilePath       string        `json:"file_path"`
}

func (q *Queries) GetSectionImageWithDetails(ctx context.Context, id string) (GetSectionImageWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getSectionImageWithDetails, id)
	var i GetSectionImageWithDetailsRow
	err := row.Scan(
		&i.SectionImageID,
		&i.SectionID,
		&i.ImageID,
		&i.IsHeader,
		&i.ID,
		&i.SiteID,
		&i.FilePath,
	)
	return i, err
}

const getSectionImagesBySectionID = `-- name: GetSectionImagesBySectionID :many
SELECT id, section_id, image_id, is_header, is_featured, order_num, created_at FROM section_images WHERE section_id = ? ORDER BY order_num
`

func (q *Queries) GetSectionImagesBySectionID(ctx context.Context, sectionID string) ([]SectionImage, error) {
	rows, err := q.db.QueryContext(ctx, getSectionImagesBySectionID, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionImage
	for rows.Next() {
		var i SectionImage
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ImageID,
			&i.IsHeader,
			&i.IsFeatured,
			&i.OrderNum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionImagesWithDetails = `-- name: GetSectionImagesWithDetails :many
SELECT
    si.id as section_image_id,
    si.section_id,
    si.is_header,
    si.is_featured,
    si.order_num,
    i.id,
    i.site_id,
    i.short_id,
    i.file_name,
    i.file_path,
    i.alt_text,
    i.title,
    i.width,
    i.height,
    i.created_at,
    i.updated_at
FROM section_images si
JOIN image i ON si.image_id = i.id
WHERE si.section_id = ?
ORDER BY si.is_header DESC, si.order_num
`

type GetSectionImagesWithDetailsRow struct {
	SectionImageID string         `json:"section_image_id"`
	SectionID      string         `json:"section_id"`
	IsHeader       sql.NullInt64  `json:"is_header"`
	IsFeatured     sql.NullInt64  `json:"is_featured"`
	OrderNum       sql.NullInt64  `json:"order_num"`
	ID             string         `json:"id"`
	SiteID         string         `json:"site_id"`
	ShortID        sql.NullString `json:"short_id"`
	FileName       string         `json:"file_name"`
	FilePath       string         `json:"file_path"`
	AltText        sql.NullString `json:"alt_text"`
	Title          sql.NullString `json:"title"`
	Width          sql.NullInt64  `json:"width"`
	Height         sql.NullInt64  `json:"height"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetSectionImagesWithDetails(ctx context.Context, sectionID string) ([]GetSectionImagesWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSectionImagesWithDetails, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSectionImagesWithDetailsRow
	for rows.Next() {
		var i GetSectionImagesWithDetailsRow
		if err := rows.Scan(
			&i.SectionImageID,
			&i.SectionID,
			&i.IsHeader,
			&i.IsFeatured,
			&i.OrderNum,
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.FileName,
			&i.FilePath,
			&i.AltText,
			&i.Title,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE image SET
    file_name = ?,
    file_path = ?,
    alt_text = ?,
    title = ?,
    width = ?,
    height = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, file_name, file_path, alt_text, title, width, height, created_by, updated_by, created_at, updated_at
`

type UpdateImageParams struct {
	FileName  string         `json:"file_name"`
	FilePath  string         `json:"file_path"`
	AltText   sql.NullString `json:"alt_text"`
	Title     sql.NullString `json:"title"`
	Width     sql.NullInt64  `json:"width"`
	Height    sql.NullInt64  `json:"height"`
	UpdatedBy sql.NullString `json:"updated_by"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, updateImage,
		arg.FileName,
		arg.FilePath,
		arg.AltText,
		arg.Title,
		arg.Width,
		arg.Height,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.FileName,
		&i.FilePath,
		&i.AltText,
		&i.Title,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImageVariant = `-- name: UpdateImageVariant :one
UPDATE image_variant SET
    kind = ?,
    blob_ref = ?,
    width = ?,
    height = ?,
    filesize_bytes = ?,
    mime = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, short_id, image_id, kind, blob_ref, width, height, filesize_bytes, mime, created_by, updated_by, created_at, updated_at
`

type UpdateImageVariantParams struct {
	Kind          string         `json:"kind"`
	BlobRef       string         `json:"blob_ref"`
	Width         sql.NullInt64  `json:"width"`
	Height        sql.NullInt64  `json:"height"`
	FilesizeBytes sql.NullInt64  `json:"filesize_bytes"`
	Mime          sql.NullString `json:"mime"`
	UpdatedBy     string         `json:"updated_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateImageVariant(ctx context.Context, arg UpdateImageVariantParams) (ImageVariant, error) {
	row := q.db.QueryRowContext(ctx, updateImageVariant,
		arg.Kind,
		arg.BlobRef,
		arg.Width,
		arg.Height,
		arg.FilesizeBytes,
		arg.Mime,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ImageVariant
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.ImageID,
		&i.Kind,
		&i.BlobRef,
		&i.Width,
		&i.Height,
		&i.FilesizeBytes,
		&i.Mime,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
