// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createImport = `-- name: CreateImport :one
INSERT INTO import (id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at
`

type CreateImportParams struct {
	ID         string         `json:"id"`
	ShortID    string         `json:"short_id"`
	FilePath   string         `json:"file_path"`
	FileHash   sql.NullString `json:"file_hash"`
	FileMtime  sql.NullTime   `json:"file_mtime"`
	ContentID  sql.NullString `json:"content_id"`
	SiteID     string         `json:"site_id"`
	UserID     string         `json:"user_id"`
	Status     string         `json:"status"`
	ImportedAt sql.NullTime   `json:"imported_at"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (Import, error) {
	row := q.db.QueryRowContext(ctx, createImport,
		arg.ID,
		arg.ShortID,
		arg.FilePath,
		arg.FileHash,
		arg.FileMtime,
		arg.ContentID,
		arg.SiteID,
		arg.UserID,
		arg.Status,
		arg.ImportedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.FilePath,
		&i.FileHash,
		&i.FileMtime,
		&i.ContentID,
		&i.SiteID,
		&i.UserID,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImport = `-- name: DeleteImport :exec
DELETE FROM import WHERE id = ?
`

func (q *Queries) DeleteImport(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImport, id)
	return err
}

const deleteImportByContentID = `-- name: DeleteImportByContentID :exec
DELETE FROM import WHERE content_id = ?
`

func (q *Queries) DeleteImportByContentID(ctx context.Context, contentID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteImportByContentID, contentID)
	return err
}

const getImport = `-- name: GetImport :one
SELECT id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at FROM import WHERE id = ?
`

func (q *Queries) GetImport(ctx context.Context, id string) (Import, error) {
	row := q.db.QueryRowContext(ctx, getImport, id)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.FilePath,
		&i.FileHash,
		&i.FileMtime,
		&i.ContentID,
		&i.SiteID,
		&i.UserID,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportByContentID = `-- name: GetImportByContentID :one
SELECT id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at FROM import WHERE content_id = ?
`

func (q *Queries) GetImportByContentID(ctx context.Context, contentID sql.NullString) (Import, error) {
	row := q.db.QueryRowContext(ctx, getImportByContentID, contentID)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.FilePath,
		&i.FileHash,
		&i.FileMtime,
		&i.ContentID,
		&i.SiteID,
		&i.UserID,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportByFilePath = `-- name: GetImportByFilePath :one
SELECT id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at FROM import WHERE file_path = ?
`

func (q *Queries) GetImportByFilePath(ctx context.Context, filePath string) (Import, error) {
	row := q.db.QueryRowContext(ctx, getImportByFilePath, filePath)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.FilePath,
		&i.FileHash,
		&i.FileMtime,
		&i.ContentID,
		&i.SiteID,
		&i.UserID,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImportsBySiteID = `-- name: ListImportsBySiteID :many
SELECT
    i.id, i.short_id, i.file_path, i.file_hash, i.file_mtime, i.content_id, i.site_id, i.user_id, i.status, i.imported_at, i.created_at, i.updated_at,
    c.heading as content_heading,
    c.updated_at as content_updated_at
FROM import i
LEFT JOIN content c ON i.content_id = c.id
WHERE i.site_id = ?
ORDER BY i.created_at DESC
`

type ListImportsBySiteIDRow struct {
	ID               string         `json:"id"`
	ShortID          string         `json:"short_id"`
	FilePath         string         `json:"file_path"`
	FileHash         sql.NullString `json:"file_hash"`
	FileMtime        sql.NullTime   `json:"file_mtime"`
	ContentID        sql.NullString `json:"content_id"`
	SiteID           string         `json:"site_id"`
	UserID           string         `json:"user_id"`
	Status           string         `json:"status"`
	ImportedAt       sql.NullTime   `json:"imported_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ContentHeading   sql.NullString `json:"content_heading"`
	ContentUpdatedAt sql.NullTime   `json:"content_updated_at"`
}

func (q *Queries) ListImportsBySiteID(ctx context.Context, siteID string) ([]ListImportsBySiteIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportsBySiteIDRow
	for rows.Next() {
		var i ListImportsBySiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.FilePath,
			&i.FileHash,
			&i.FileMtime,
			&i.ContentID,
			&i.SiteID,
			&i.UserID,
			&i.Status,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHeading,
			&i.ContentUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImport = `-- name: UpdateImport :one
UPDATE import SET
    file_hash = ?,
    file_mtime = ?,
    content_id = ?,
    status = ?,
    imported_at = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at
`

type UpdateImportParams struct {
	FileHash   sql.NullString `json:"file_hash"`
	FileMtime  sql.NullTime   `json:"file_mtime"`
	ContentID  sql.NullString `json:"content_id"`
	Status     string         `json:"status"`
	ImportedAt sql.NullTime   `json:"imported_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateImport(ctx context.Context, arg UpdateImportParams) (Import, error) {
	row := q.db.QueryRowContext(ctx, updateImport,
		arg.FileHash,
		arg.FileMtime,
		arg.ContentID,
		arg.Status,
		arg.ImportedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.FilePath,
		&i.FileHash,
		&i.FileMtime,
		&i.ContentID,
		&i.SiteID,
		&i.UserID,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportStatus = `-- name: UpdateImportStatus :one
UPDATE import SET
    status = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, short_id, file_path, file_hash, file_mtime, content_id, site_id, user_id, status, imported_at, created_at, updated_at
`

type UpdateImportStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateImportStatus(ctx context.Context, arg UpdateImportStatusParams) (Import, error) {
	row := q.db.QueryRowContext(ctx, updateImportStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.FilePath,
		&i.FileHash,
		&i.FileMtime,
		&i.ContentID,
		&i.SiteID,
		&i.UserID,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
