// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: layout.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createLayout = `-- name: CreateLayout :one
INSERT INTO layout (id, site_id, short_id, name, description, code, css, exclude_default_css, header_image_id, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, name, description, code, header_image_id, created_by, updated_by, created_at, updated_at, css, exclude_default_css
`

type CreateLayoutParams struct {
	ID                string         `json:"id"`
	SiteID            string         `json:"site_id"`
	ShortID           sql.NullString `json:"short_id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	Code              sql.NullString `json:"code"`
	Css               sql.NullString `json:"css"`
	ExcludeDefaultCss sql.NullInt64  `json:"exclude_default_css"`
	HeaderImageID     sql.NullString `json:"header_image_id"`
	CreatedBy         sql.NullString `json:"created_by"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateLayout(ctx context.Context, arg CreateLayoutParams) (Layout, error) {
	row := q.db.QueryRowContext(ctx, createLayout,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.Css,
		arg.ExcludeDefaultCss,
		arg.HeaderImageID,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Layout
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.HeaderImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Css,
		&i.ExcludeDefaultCss,
	)
	return i, err
}

const deleteLayout = `-- name: DeleteLayout :exec
DELETE FROM layout WHERE id = ?
`

func (q *Queries) DeleteLayout(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLayout, id)
	return err
}

const getLayout = `-- name: GetLayout :one
SELECT id, site_id, short_id, name, description, code, header_image_id, created_by, updated_by, created_at, updated_at, css, exclude_default_css FROM layout WHERE id = ?
`

func (q *Queries) GetLayout(ctx context.Context, id string) (Layout, error) {
	row := q.db.QueryRowContext(ctx, getLayout, id)
	var i Layout
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.HeaderImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Css,
		&i.ExcludeDefaultCss,
	)
	return i, err
}

const getLayoutByName = `-- name: GetLayoutByName :one
SELECT id, site_id, short_id, name, description, code, header_image_id, created_by, updated_by, created_at, updated_at, css, exclude_default_css FROM layout WHERE site_id = ? AND name = ?
`

type GetLayoutByNameParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetLayoutByName(ctx context.Context, arg GetLayoutByNameParams) (Layout, error) {
	row := q.db.QueryRowContext(ctx, getLayoutByName, arg.SiteID, arg.Name)
	var i Layout
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.HeaderImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Css,
		&i.ExcludeDefaultCss,
	)
	return i, err
}

const getLayoutsBySiteID = `-- name: GetLayoutsBySiteID :many
SELECT id, site_id, short_id, name, description, code, header_image_id, created_by, updated_by, created_at, updated_at, css, exclude_default_css FROM layout WHERE site_id = ? ORDER BY name
`

func (q *Queries) GetLayoutsBySiteID(ctx context.Context, siteID string) ([]Layout, error) {
	rows, err := q.db.QueryContext(ctx, getLayoutsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Layout
	for rows.Next() {
		var i Layout
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.HeaderImageID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Css,
			&i.ExcludeDefaultCss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLayout = `-- name: UpdateLayout :one
UPDATE layout SET
    name = ?,
    description = ?,
    code = ?,
    css = ?,
    exclude_default_css = ?,
    header_image_id = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, name, description, code, header_image_id, created_by, updated_by, created_at, updated_at, css, exclude_default_css
`

type UpdateLayoutParams struct {
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	Code              sql.NullString `json:"code"`
	Css               sql.NullString `json:"css"`
	ExcludeDefaultCss sql.NullInt64  `json:"exclude_default_css"`
	HeaderImageID     sql.NullString `json:"header_image_id"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateLayout(ctx context.Context, arg UpdateLayoutParams) (Layout, error) {
	row := q.db.QueryRowContext(ctx, updateLayout,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.Css,
		arg.ExcludeDefaultCss,
		arg.HeaderImageID,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Layout
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.HeaderImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Css,
		&i.ExcludeDefaultCss,
	)
	return i, err
}
