// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMeta = `-- name: CreateMeta :one
INSERT INTO meta (id, site_id, short_id, content_id, summary, excerpt, description, keywords, robots, canonical_url, sitemap, table_of_contents, share, comments, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, content_id, summary, excerpt, description, keywords, robots, canonical_url, sitemap, table_of_contents, share, comments, created_by, updated_by, created_at, updated_at
`

type CreateMetaParams struct {
	ID              string         `json:"id"`
	SiteID          string         `json:"site_id"`
	ShortID         sql.NullString `json:"short_id"`
	ContentID       string         `json:"content_id"`
	Summary         sql.NullString `json:"summary"`
	Excerpt         sql.NullString `json:"excerpt"`
	Description     sql.NullString `json:"description"`
	Keywords        sql.NullString `json:"keywords"`
	Robots          sql.NullString `json:"robots"`
	CanonicalUrl    sql.NullString `json:"canonical_url"`
	Sitemap         sql.NullString `json:"sitemap"`
	TableOfContents sql.NullInt64  `json:"table_of_contents"`
	Share           sql.NullInt64  `json:"share"`
	Comments        sql.NullInt64  `json:"comments"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateMeta(ctx context.Context, arg CreateMetaParams) (Meta, error) {
	row := q.db.QueryRowContext(ctx, createMeta,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.ContentID,
		arg.Summary,
		arg.Excerpt,
		arg.Description,
		arg.Keywords,
		arg.Robots,
		arg.CanonicalUrl,
		arg.Sitemap,
		arg.TableOfContents,
		arg.Share,
		arg.Comments,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Meta
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.ContentID,
		&i.Summary,
		&i.Excerpt,
		&i.Description,
		&i.Keywords,
		&i.Robots,
		&i.CanonicalUrl,
		&i.Sitemap,
		&i.TableOfContents,
		&i.Share,
		&i.Comments,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeta = `-- name: DeleteMeta :exec
DELETE FROM meta WHERE id = ?
`

func (q *Queries) DeleteMeta(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMeta, id)
	return err
}

const deleteMetaByContentID = `-- name: DeleteMetaByContentID :exec
DELETE FROM meta WHERE content_id = ?
`

func (q *Queries) DeleteMetaByContentID(ctx context.Context, contentID string) error {
	_, err := q.db.ExecContext(ctx, deleteMetaByContentID, contentID)
	return err
}

const getMeta = `-- name: GetMeta :one
SELECT id, site_id, short_id, content_id, summary, excerpt, description, keywords, robots, canonical_url, sitemap, table_of_contents, share, comments, created_by, updated_by, created_at, updated_at FROM meta WHERE id = ?
`

func (q *Queries) GetMeta(ctx context.Context, id string) (Meta, error) {
	row := q.db.QueryRowContext(ctx, getMeta, id)
	var i Meta
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.ContentID,
		&i.Summary,
		&i.Excerpt,
		&i.Description,
		&i.Keywords,
		&i.Robots,
		&i.CanonicalUrl,
		&i.Sitemap,
		&i.TableOfContents,
		&i.Share,
		&i.Comments,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetaByContentID = `-- name: GetMetaByContentID :one
SELECT id, site_id, short_id, content_id, summary, excerpt, description, keywords, robots, canonical_url, sitemap, table_of_contents, share, comments, created_by, updated_by, created_at, updated_at FROM meta WHERE content_id = ?
`

func (q *Queries) GetMetaByContentID(ctx context.Context, contentID string) (Meta, error) {
	row := q.db.QueryRowContext(ctx, getMetaByContentID, contentID)
	var i Meta
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.ContentID,
		&i.Summary,
		&i.Excerpt,
		&i.Description,
		&i.Keywords,
		&i.Robots,
		&i.CanonicalUrl,
		&i.Sitemap,
		&i.TableOfContents,
		&i.Share,
		&i.Comments,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMeta = `-- name: UpdateMeta :one
UPDATE meta SET
    summary = ?,
    excerpt = ?,
    description = ?,
    keywords = ?,
    robots = ?,
    canonical_url = ?,
    sitemap = ?,
    table_of_contents = ?,
    share = ?,
    comments = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, content_id, summary, excerpt, description, keywords, robots, canonical_url, sitemap, table_of_contents, share, comments, created_by, updated_by, created_at, updated_at
`

type UpdateMetaParams struct {
	Summary         sql.NullString `json:"summary"`
	Excerpt         sql.NullString `json:"excerpt"`
	Description     sql.NullString `json:"description"`
	Keywords        sql.NullString `json:"keywords"`
	Robots          sql.NullString `json:"robots"`
	CanonicalUrl    sql.NullString `json:"canonical_url"`
	Sitemap         sql.NullString `json:"sitemap"`
	TableOfContents sql.NullInt64  `json:"table_of_contents"`
	Share           sql.NullInt64  `json:"share"`
	Comments        sql.NullInt64  `json:"comments"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateMeta(ctx context.Context, arg UpdateMetaParams) (Meta, error) {
	row := q.db.QueryRowContext(ctx, updateMeta,
		arg.Summary,
		arg.Excerpt,
		arg.Description,
		arg.Keywords,
		arg.Robots,
		arg.CanonicalUrl,
		arg.Sitemap,
		arg.TableOfContents,
		arg.Share,
		arg.Comments,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Meta
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.ContentID,
		&i.Summary,
		&i.Excerpt,
		&i.Description,
		&i.Keywords,
		&i.Robots,
		&i.CanonicalUrl,
		&i.Sitemap,
		&i.TableOfContents,
		&i.Share,
		&i.Comments,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
