// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Content struct {
	ID                string         `json:"id"`
	SiteID            string         `json:"site_id"`
	UserID            sql.NullString `json:"user_id"`
	ShortID           sql.NullString `json:"short_id"`
	SectionID         sql.NullString `json:"section_id"`
	Kind              sql.NullString `json:"kind"`
	Heading           string         `json:"heading"`
	Summary           sql.NullString `json:"summary"`
	Body              sql.NullString `json:"body"`
	Draft             sql.NullInt64  `json:"draft"`
	Featured          sql.NullInt64  `json:"featured"`
	Series            sql.NullString `json:"series"`
	SeriesOrder       sql.NullInt64  `json:"series_order"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	CreatedBy         sql.NullString `json:"created_by"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	ContributorID     sql.NullString `json:"contributor_id"`
	ContributorHandle string         `json:"contributor_handle"`
	AuthorUsername    string         `json:"author_username"`
	HeroTitleDark     sql.NullInt64  `json:"hero_title_dark"`
	ImagesMeta        sql.NullString `json:"images_meta"`
}

type ContentImage struct {
	ID         string        `json:"id"`
	ContentID  string        `json:"content_id"`
	ImageID    string        `json:"image_id"`
	IsHeader   sql.NullInt64 `json:"is_header"`
	IsFeatured sql.NullInt64 `json:"is_featured"`
	OrderNum   sql.NullInt64 `json:"order_num"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type ContentTag struct {
	ID        string       `json:"id"`
	ContentID string       `json:"content_id"`
	TagID     string       `json:"tag_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Contributor struct {
	ID          string         `json:"id"`
	ShortID     string         `json:"short_id"`
	SiteID      string         `json:"site_id"`
	ProfileID   sql.NullString `json:"profile_id"`
	Handle      string         `json:"handle"`
	Name        string         `json:"name"`
	Surname     string         `json:"surname"`
	Bio         string         `json:"bio"`
	SocialLinks string         `json:"social_links"`
	Role        string         `json:"role"`
	CreatedBy   string         `json:"created_by"`
	UpdatedBy   string         `json:"updated_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Image struct {
	ID             string         `json:"id"`
	SiteID         string         `json:"site_id"`
	ShortID        sql.NullString `json:"short_id"`
	FileName       string         `json:"file_name"`
	FilePath       string         `json:"file_path"`
	AltText        sql.NullString `json:"alt_text"`
	Title          sql.NullString `json:"title"`
	Attribution    sql.NullString `json:"attribution"`
	AttributionUrl sql.NullString `json:"attribution_url"`
	Width          sql.NullInt64  `json:"width"`
	Height         sql.NullInt64  `json:"height"`
	CreatedBy      sql.NullString `json:"created_by"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type ImageVariant struct {
	ID            string         `json:"id"`
	ShortID       string         `json:"short_id"`
	ImageID       string         `json:"image_id"`
	Kind          string         `json:"kind"`
	BlobRef       string         `json:"blob_ref"`
	Width         sql.NullInt64  `json:"width"`
	Height        sql.NullInt64  `json:"height"`
	FilesizeBytes sql.NullInt64  `json:"filesize_bytes"`
	Mime          sql.NullString `json:"mime"`
	CreatedBy     string         `json:"created_by"`
	UpdatedBy     string         `json:"updated_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Layout struct {
	ID            string         `json:"id"`
	SiteID        string         `json:"site_id"`
	ShortID       sql.NullString `json:"short_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Code          sql.NullString `json:"code"`
	HeaderImageID sql.NullString `json:"header_image_id"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Meta struct {
	ID              string         `json:"id"`
	SiteID          string         `json:"site_id"`
	ShortID         sql.NullString `json:"short_id"`
	ContentID       string         `json:"content_id"`
	Summary         sql.NullString `json:"summary"`
	Excerpt         sql.NullString `json:"excerpt"`
	Description     sql.NullString `json:"description"`
	Keywords        sql.NullString `json:"keywords"`
	Robots          sql.NullString `json:"robots"`
	CanonicalUrl    sql.NullString `json:"canonical_url"`
	Sitemap         sql.NullString `json:"sitemap"`
	TableOfContents sql.NullInt64  `json:"table_of_contents"`
	Share           sql.NullInt64  `json:"share"`
	Comments        sql.NullInt64  `json:"comments"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Profile struct {
	ID          string    `json:"id"`
	ShortID     string    `json:"short_id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Surname     string    `json:"surname"`
	Bio         string    `json:"bio"`
	SocialLinks string    `json:"social_links"`
	PhotoPath   string    `json:"photo_path"`
	CreatedBy   string    `json:"created_by"`
	UpdatedBy   string    `json:"updated_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Section struct {
	ID            string         `json:"id"`
	SiteID        string         `json:"site_id"`
	ShortID       sql.NullString `json:"short_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Path          sql.NullString `json:"path"`
	LayoutID      sql.NullString `json:"layout_id"`
	LayoutName    sql.NullString `json:"layout_name"`
	HeroTitleDark sql.NullInt64  `json:"hero_title_dark"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type SectionImage struct {
	ID         string        `json:"id"`
	SectionID  string        `json:"section_id"`
	ImageID    string        `json:"image_id"`
	IsHeader   sql.NullInt64 `json:"is_header"`
	IsFeatured sql.NullInt64 `json:"is_featured"`
	OrderNum   sql.NullInt64 `json:"order_num"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Setting struct {
	ID          string         `json:"id"`
	SiteID      string         `json:"site_id"`
	ShortID     sql.NullString `json:"short_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Value       sql.NullString `json:"value"`
	RefKey      sql.NullString `json:"ref_key"`
	System      sql.NullInt64  `json:"system"`
	Category    sql.NullString `json:"category"`
	Position    sql.NullInt64  `json:"position"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Site struct {
	ID                string         `json:"id"`
	ShortID           string         `json:"short_id"`
	Name              string         `json:"name"`
	Slug              string         `json:"slug"`
	Active            int64          `json:"active"`
	DefaultLayoutID   sql.NullString `json:"default_layout_id"`
	DefaultLayoutName sql.NullString `json:"default_layout_name"`
	CreatedBy         string         `json:"created_by"`
	UpdatedBy         string         `json:"updated_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type Tag struct {
	ID        string         `json:"id"`
	SiteID    string         `json:"site_id"`
	ShortID   sql.NullString `json:"short_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	CreatedBy sql.NullString `json:"created_by"`
	UpdatedBy sql.NullString `json:"updated_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                 string         `json:"id"`
	ShortID            string         `json:"short_id"`
	Email              string         `json:"email"`
	PasswordHash       string         `json:"password_hash"`
	Name               string         `json:"name"`
	Status             string         `json:"status"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	MustChangePassword int64          `json:"must_change_password"`
	Roles              string         `json:"roles"`
	ProfileID          sql.NullString `json:"profile_id"`
}
