// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: param.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createParam = `-- name: CreateParam :one
INSERT INTO param (id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at
`

type CreateParamParams struct {
	ID          string         `json:"id"`
	SiteID      string         `json:"site_id"`
	ShortID     sql.NullString `json:"short_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Value       sql.NullString `json:"value"`
	RefKey      sql.NullString `json:"ref_key"`
	System      sql.NullInt64  `json:"system"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateParam(ctx context.Context, arg CreateParamParams) (Param, error) {
	row := q.db.QueryRowContext(ctx, createParam,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.Name,
		arg.Description,
		arg.Value,
		arg.RefKey,
		arg.System,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParam = `-- name: DeleteParam :exec
DELETE FROM param WHERE id = ?
`

func (q *Queries) DeleteParam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteParam, id)
	return err
}

const getParam = `-- name: GetParam :one
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at FROM param WHERE id = ?
`

func (q *Queries) GetParam(ctx context.Context, id string) (Param, error) {
	row := q.db.QueryRowContext(ctx, getParam, id)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParamByName = `-- name: GetParamByName :one
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at FROM param WHERE site_id = ? AND name = ?
`

type GetParamByNameParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetParamByName(ctx context.Context, arg GetParamByNameParams) (Param, error) {
	row := q.db.QueryRowContext(ctx, getParamByName, arg.SiteID, arg.Name)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParamByRefKey = `-- name: GetParamByRefKey :one
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at FROM param WHERE site_id = ? AND ref_key = ?
`

type GetParamByRefKeyParams struct {
	SiteID string         `json:"site_id"`
	RefKey sql.NullString `json:"ref_key"`
}

func (q *Queries) GetParamByRefKey(ctx context.Context, arg GetParamByRefKeyParams) (Param, error) {
	row := q.db.QueryRowContext(ctx, getParamByRefKey, arg.SiteID, arg.RefKey)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParamsBySiteID = `-- name: GetParamsBySiteID :many
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at FROM param WHERE site_id = ? ORDER BY name
`

func (q *Queries) GetParamsBySiteID(ctx context.Context, siteID string) ([]Param, error) {
	rows, err := q.db.QueryContext(ctx, getParamsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Param
	for rows.Next() {
		var i Param
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.Name,
			&i.Description,
			&i.Value,
			&i.RefKey,
			&i.System,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParam = `-- name: UpdateParam :one
UPDATE param SET
    name = ?,
    description = ?,
    value = ?,
    ref_key = ?,
    system = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at
`

type UpdateParamParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Value       sql.NullString `json:"value"`
	RefKey      sql.NullString `json:"ref_key"`
	System      sql.NullInt64  `json:"system"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateParam(ctx context.Context, arg UpdateParamParams) (Param, error) {
	row := q.db.QueryRowContext(ctx, updateParam,
		arg.Name,
		arg.Description,
		arg.Value,
		arg.RefKey,
		arg.System,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
