// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"
	"time"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profile (id, site_id, short_id, slug, name, surname, bio, social_links, photo_path, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, slug, name, surname, bio, social_links, photo_path, created_by, updated_by, created_at, updated_at
`

type CreateProfileParams struct {
	ID          string    `json:"id"`
	SiteID      string    `json:"site_id"`
	ShortID     string    `json:"short_id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Surname     string    `json:"surname"`
	Bio         string    `json:"bio"`
	SocialLinks string    `json:"social_links"`
	PhotoPath   string    `json:"photo_path"`
	CreatedBy   string    `json:"created_by"`
	UpdatedBy   string    `json:"updated_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.Slug,
		arg.Name,
		arg.Surname,
		arg.Bio,
		arg.SocialLinks,
		arg.PhotoPath,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Slug,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profile WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, site_id, short_id, slug, name, surname, bio, social_links, photo_path, created_by, updated_by, created_at, updated_at FROM profile WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Slug,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileBySlug = `-- name: GetProfileBySlug :one
SELECT id, site_id, short_id, slug, name, surname, bio, social_links, photo_path, created_by, updated_by, created_at, updated_at FROM profile WHERE site_id = ? AND slug = ?
`

type GetProfileBySlugParams struct {
	SiteID string `json:"site_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetProfileBySlug(ctx context.Context, arg GetProfileBySlugParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileBySlug, arg.SiteID, arg.Slug)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Slug,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, site_id, short_id, slug, name, surname, bio, social_links, photo_path, created_by, updated_by, created_at, updated_at FROM profile WHERE site_id = ? ORDER BY name ASC
`

func (q *Queries) ListProfiles(ctx context.Context, siteID string) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.Slug,
			&i.Name,
			&i.Surname,
			&i.Bio,
			&i.SocialLinks,
			&i.PhotoPath,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profile SET
    slug = ?,
    name = ?,
    surname = ?,
    bio = ?,
    social_links = ?,
    photo_path = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, slug, name, surname, bio, social_links, photo_path, created_by, updated_by, created_at, updated_at
`

type UpdateProfileParams struct {
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Surname     string    `json:"surname"`
	Bio         string    `json:"bio"`
	SocialLinks string    `json:"social_links"`
	PhotoPath   string    `json:"photo_path"`
	UpdatedBy   string    `json:"updated_by"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.Slug,
		arg.Name,
		arg.Surname,
		arg.Bio,
		arg.SocialLinks,
		arg.PhotoPath,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Slug,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.SocialLinks,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
