// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddTagToContent(ctx context.Context, arg AddTagToContentParams) error
	CountContent(ctx context.Context, siteID string) (int64, error)
	CountSearchContent(ctx context.Context, arg CountSearchContentParams) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
	CreateContentImage(ctx context.Context, arg CreateContentImageParams) error
	CreateContributor(ctx context.Context, arg CreateContributorParams) (Contributor, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateImageVariant(ctx context.Context, arg CreateImageVariantParams) (ImageVariant, error)
	CreateImport(ctx context.Context, arg CreateImportParams) (Import, error)
	CreateLayout(ctx context.Context, arg CreateLayoutParams) (Layout, error)
	CreateMeta(ctx context.Context, arg CreateMetaParams) (Meta, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	CreateSectionImage(ctx context.Context, arg CreateSectionImageParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIToken(ctx context.Context, id string) error
	DeleteContent(ctx context.Context, id string) error
	DeleteContentImage(ctx context.Context, id string) error
	DeleteContentImageByContentAndImage(ctx context.Context, arg DeleteContentImageByContentAndImageParams) error
	DeleteContributor(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteImage(ctx context.Context, id string) error
	DeleteImageVariant(ctx context.Context, id string) error
	DeleteImport(ctx context.Context, id string) error
	DeleteImportByContentID(ctx context.Context, contentID sql.NullString) error
	DeleteLayout(ctx context.Context, id string) error
	DeleteMeta(ctx context.Context, id string) error
	DeleteMetaByContentID(ctx context.Context, contentID string) error
	DeleteProfile(ctx context.Context, id string) error
	DeleteSection(ctx context.Context, id string) error
	DeleteSectionImage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSetting(ctx context.Context, id string) error
	DeleteSite(ctx context.Context, id string) error
	DeleteTag(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAllContentImagesBySiteID(ctx context.Context, siteID string) ([]GetAllContentImagesBySiteIDRow, error)
	GetAllContentWithMeta(ctx context.Context, siteID string) ([]GetAllContentWithMetaRow, error)
	GetContent(ctx context.Context, id string) (Content, error)
	GetContentBySectionID(ctx context.Context, sectionID sql.NullString) ([]Content, error)
	GetContentBySiteID(ctx context.Context, siteID string) ([]Content, error)
	GetContentForTag(ctx context.Context, tagID string) ([]Content, error)
	GetContentImageWithDetails(ctx context.Context, id string) (GetContentImageWithDetailsRow, error)
	GetContentImagesByContentID(ctx context.Context, contentID string) ([]ContentImage, error)
	GetContentImagesWithDetails(ctx context.Context, contentID string) ([]GetContentImagesWithDetailsRow, error)
	GetContentWithMeta(ctx context.Context, id string) (GetContentWithMetaRow, error)
	GetContentWithPagination(ctx context.Context, arg GetContentWithPaginationParams) ([]Content, error)
	GetContributor(ctx context.Context, id string) (Contributor, error)
	GetContributorByHandle(ctx context.Context, arg GetContributorByHandleParams) (Contributor, error)
	GetImage(ctx context.Context, id string) (Image, error)
	GetImageByPath(ctx context.Context, arg GetImageByPathParams) (Image, error)
	GetImageByShortID(ctx context.Context, shortID sql.NullString) (Image, error)
	GetImageVariant(ctx context.Context, id string) (ImageVariant, error)
	GetImageVariantsByImageID(ctx context.Context, imageID string) ([]ImageVariant, error)
	GetImagesBySiteID(ctx context.Context, siteID string) ([]Image, error)
	GetImport(ctx context.Context, id string) (Import, error)
	GetImportByContentID(ctx context.Context, contentID sql.NullString) (Import, error)
	GetImportByFilePath(ctx context.Context, filePath string) (Import, error)
	GetLayout(ctx context.Context, id string) (Layout, error)
	GetLayoutByName(ctx context.Context, arg GetLayoutByNameParams) (Layout, error)
	GetLayoutsBySiteID(ctx context.Context, siteID string) ([]Layout, error)
	GetMeta(ctx context.Context, id string) (Meta, error)
	GetMetaByContentID(ctx context.Context, contentID string) (Meta, error)
	GetProfile(ctx context.Context, id string) (Profile, error)
	GetProfileBySlug(ctx context.Context, arg GetProfileBySlugParams) (Profile, error)
	GetPublishedContentBySiteID(ctx context.Context, siteID string) ([]Content, error)
	GetSection(ctx context.Context, id string) (Section, error)
	GetSectionByPath(ctx context.Context, arg GetSectionByPathParams) (Section, error)
	GetSectionImageWithDetails(ctx context.Context, id string) (GetSectionImageWithDetailsRow, error)
	GetSectionImagesBySectionID(ctx context.Context, sectionID string) ([]SectionImage, error)
	GetSectionImagesWithDetails(ctx context.Context, sectionID string) ([]GetSectionImagesWithDetailsRow, error)
	GetSectionsBySiteID(ctx context.Context, siteID string) ([]Section, error)
	GetSectionsWithHeaderImage(ctx context.Context, siteID string) ([]GetSectionsWithHeaderImageRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSetting(ctx context.Context, id string) (Setting, error)
	GetSettingByName(ctx context.Context, arg GetSettingByNameParams) (Setting, error)
	GetSettingByRefKey(ctx context.Context, arg GetSettingByRefKeyParams) (Setting, error)
	GetSettingsBySiteID(ctx context.Context, siteID string) ([]Setting, error)
	GetSite(ctx context.Context, id string) (Site, error)
	GetSiteBySlug(ctx context.Context, slug string) (Site, error)
	GetTag(ctx context.Context, id string) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetTagBySlug(ctx context.Context, arg GetTagBySlugParams) (Tag, error)
	GetTagsBySiteID(ctx context.Context, siteID string) ([]Tag, error)
	GetTagsForContent(ctx context.Context, contentID string) ([]Tag, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	GetUserWithProfile(ctx context.Context, name string) (GetUserWithProfileRow, error)
	GetValidSession(ctx context.Context, id string) (Session, error)
	ListAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	ListAllSites(ctx context.Context) ([]Site, error)
	ListContributorsBySiteID(ctx context.Context, siteID string) ([]Contributor, error)
	ListContributorsWithProfile(ctx context.Context, siteID string) ([]ListContributorsWithProfileRow, error)
	ListImportsBySiteID(ctx context.Context, siteID string) ([]ListImportsBySiteIDRow, error)
	ListProfiles(ctx context.Context, siteID string) ([]Profile, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveAllTagsFromContent(ctx context.Context, contentID string) error
	RemoveTagFromContent(ctx context.Context, arg RemoveTagFromContentParams) error
	SearchContent(ctx context.Context, arg SearchContentParams) ([]Content, error)
	SetContributorProfile(ctx context.Context, arg SetContributorProfileParams) error
	SetUserProfile(ctx context.Context, arg SetUserProfileParams) error
	UpdateAPITokenLastUsed(ctx context.Context, arg UpdateAPITokenLastUsedParams) error
	UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error)
	UpdateContributor(ctx context.Context, arg UpdateContributorParams) (Contributor, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
	UpdateImageVariant(ctx context.Context, arg UpdateImageVariantParams) (ImageVariant, error)
	UpdateImport(ctx context.Context, arg UpdateImportParams) (Import, error)
	UpdateImportStatus(ctx context.Context, arg UpdateImportStatusParams) (Import, error)
	UpdateLayout(ctx context.Context, arg UpdateLayoutParams) (Layout, error)
	UpdateMeta(ctx context.Context, arg UpdateMetaParams) (Meta, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
