// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddTagToContent(ctx context.Context, arg AddTagToContentParams) error
	CountContent(ctx context.Context, siteID string) (int64, error)
	CountSearchContent(ctx context.Context, arg CountSearchContentParams) (int64, error)
	CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
	CreateContentImage(ctx context.Context, arg CreateContentImageParams) error
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateImageVariant(ctx context.Context, arg CreateImageVariantParams) (ImageVariant, error)
	CreateLayout(ctx context.Context, arg CreateLayoutParams) (Layout, error)
	CreateMeta(ctx context.Context, arg CreateMetaParams) (Meta, error)
	CreateParam(ctx context.Context, arg CreateParamParams) (Param, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	CreateSectionImage(ctx context.Context, arg CreateSectionImageParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteContent(ctx context.Context, id string) error
	DeleteContentImage(ctx context.Context, id string) error
	DeleteContentImageByContentAndImage(ctx context.Context, arg DeleteContentImageByContentAndImageParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteImage(ctx context.Context, id string) error
	DeleteImageVariant(ctx context.Context, id string) error
	DeleteLayout(ctx context.Context, id string) error
	DeleteMeta(ctx context.Context, id string) error
	DeleteMetaByContentID(ctx context.Context, contentID string) error
	DeleteParam(ctx context.Context, id string) error
	DeleteSection(ctx context.Context, id string) error
	DeleteSectionImage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSite(ctx context.Context, id string) error
	DeleteTag(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetAllContentWithMeta(ctx context.Context, siteID string) ([]GetAllContentWithMetaRow, error)
	GetContent(ctx context.Context, id string) (Content, error)
	GetContentBySectionID(ctx context.Context, sectionID sql.NullString) ([]Content, error)
	GetContentBySiteID(ctx context.Context, siteID string) ([]Content, error)
	GetContentForTag(ctx context.Context, tagID string) ([]Content, error)
	GetContentImagesByContentID(ctx context.Context, contentID string) ([]ContentImage, error)
	GetContentWithMeta(ctx context.Context, id string) (GetContentWithMetaRow, error)
	GetContentWithPagination(ctx context.Context, arg GetContentWithPaginationParams) ([]Content, error)
	GetImage(ctx context.Context, id string) (Image, error)
	GetImageByPath(ctx context.Context, arg GetImageByPathParams) (Image, error)
	GetImageByShortID(ctx context.Context, shortID sql.NullString) (Image, error)
	GetImageVariant(ctx context.Context, id string) (ImageVariant, error)
	GetImageVariantsByImageID(ctx context.Context, imageID string) ([]ImageVariant, error)
	GetImagesBySiteID(ctx context.Context, siteID string) ([]Image, error)
	GetLayout(ctx context.Context, id string) (Layout, error)
	GetLayoutByName(ctx context.Context, arg GetLayoutByNameParams) (Layout, error)
	GetLayoutsBySiteID(ctx context.Context, siteID string) ([]Layout, error)
	GetMeta(ctx context.Context, id string) (Meta, error)
	GetMetaByContentID(ctx context.Context, contentID string) (Meta, error)
	GetParam(ctx context.Context, id string) (Param, error)
	GetParamByName(ctx context.Context, arg GetParamByNameParams) (Param, error)
	GetParamByRefKey(ctx context.Context, arg GetParamByRefKeyParams) (Param, error)
	GetParamsBySiteID(ctx context.Context, siteID string) ([]Param, error)
	GetPublishedContentBySiteID(ctx context.Context, siteID string) ([]Content, error)
	GetSection(ctx context.Context, id string) (Section, error)
	GetSectionByPath(ctx context.Context, arg GetSectionByPathParams) (Section, error)
	GetSectionImagesBySectionID(ctx context.Context, sectionID string) ([]SectionImage, error)
	GetSectionsBySiteID(ctx context.Context, siteID string) ([]Section, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSite(ctx context.Context, id string) (Site, error)
	GetSiteBySlug(ctx context.Context, slug string) (Site, error)
	GetTag(ctx context.Context, id string) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetTagBySlug(ctx context.Context, arg GetTagBySlugParams) (Tag, error)
	GetTagsBySiteID(ctx context.Context, siteID string) ([]Tag, error)
	GetTagsForContent(ctx context.Context, contentID string) ([]Tag, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetValidSession(ctx context.Context, id string) (Session, error)
	ListAllSites(ctx context.Context) ([]Site, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveAllTagsFromContent(ctx context.Context, contentID string) error
	RemoveTagFromContent(ctx context.Context, arg RemoveTagFromContentParams) error
	SearchContent(ctx context.Context, arg SearchContentParams) ([]Content, error)
	UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
	UpdateImageVariant(ctx context.Context, arg UpdateImageVariantParams) (ImageVariant, error)
	UpdateLayout(ctx context.Context, arg UpdateLayoutParams) (Layout, error)
	UpdateMeta(ctx context.Context, arg UpdateMetaParams) (Meta, error)
	UpdateParam(ctx context.Context, arg UpdateParamParams) (Param, error)
	UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
