// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: section.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSection = `-- name: CreateSection :one
INSERT INTO section (id, site_id, short_id, name, description, path, layout_id, layout_name, hero_title_dark, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, name, description, path, layout_id, layout_name, hero_title_dark, created_by, updated_by, created_at, updated_at
`

type CreateSectionParams struct {
	ID            string         `json:"id"`
	SiteID        string         `json:"site_id"`
	ShortID       sql.NullString `json:"short_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Path          sql.NullString `json:"path"`
	LayoutID      sql.NullString `json:"layout_id"`
	LayoutName    sql.NullString `json:"layout_name"`
	HeroTitleDark sql.NullInt64  `json:"hero_title_dark"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, createSection,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.Name,
		arg.Description,
		arg.Path,
		arg.LayoutID,
		arg.LayoutName,
		arg.HeroTitleDark,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.LayoutID,
		&i.LayoutName,
		&i.HeroTitleDark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSection = `-- name: DeleteSection :exec
DELETE FROM section WHERE id = ?
`

func (q *Queries) DeleteSection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSection, id)
	return err
}

const getSection = `-- name: GetSection :one
SELECT id, site_id, short_id, name, description, path, layout_id, layout_name, hero_title_dark, created_by, updated_by, created_at, updated_at FROM section WHERE id = ?
`

func (q *Queries) GetSection(ctx context.Context, id string) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSection, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.LayoutID,
		&i.LayoutName,
		&i.HeroTitleDark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionByPath = `-- name: GetSectionByPath :one
SELECT id, site_id, short_id, name, description, path, layout_id, layout_name, hero_title_dark, created_by, updated_by, created_at, updated_at FROM section WHERE site_id = ? AND path = ?
`

type GetSectionByPathParams struct {
	SiteID string         `json:"site_id"`
	Path   sql.NullString `json:"path"`
}

func (q *Queries) GetSectionByPath(ctx context.Context, arg GetSectionByPathParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSectionByPath, arg.SiteID, arg.Path)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.LayoutID,
		&i.LayoutName,
		&i.HeroTitleDark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionsBySiteID = `-- name: GetSectionsBySiteID :many
SELECT id, site_id, short_id, name, description, path, layout_id, layout_name, hero_title_dark, created_by, updated_by, created_at, updated_at FROM section WHERE site_id = ? ORDER BY path
`

func (q *Queries) GetSectionsBySiteID(ctx context.Context, siteID string) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, getSectionsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.Name,
			&i.Description,
			&i.Path,
			&i.LayoutID,
			&i.LayoutName,
			&i.HeroTitleDark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionsWithHeaderImage = `-- name: GetSectionsWithHeaderImage :many
SELECT
    s.id, s.site_id, s.short_id, s.name, s.description, s.path, s.layout_id, s.layout_name, s.hero_title_dark, s.created_by, s.updated_by, s.created_at, s.updated_at,
    hi.file_path as header_image_path,
    hi.alt_text as header_image_alt
FROM section s
LEFT JOIN section_images si ON s.id = si.section_id AND si.is_header = 1
LEFT JOIN image hi ON si.image_id = hi.id
WHERE s.site_id = ?
ORDER BY s.path
`

type GetSectionsWithHeaderImageRow struct {
	ID              string         `json:"id"`
	SiteID          string         `json:"site_id"`
	ShortID         sql.NullString `json:"short_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Path            sql.NullString `json:"path"`
	LayoutID        sql.NullString `json:"layout_id"`
	LayoutName      sql.NullString `json:"layout_name"`
	HeroTitleDark   sql.NullInt64  `json:"hero_title_dark"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	HeaderImagePath sql.NullString `json:"header_image_path"`
	HeaderImageAlt  sql.NullString `json:"header_image_alt"`
}

func (q *Queries) GetSectionsWithHeaderImage(ctx context.Context, siteID string) ([]GetSectionsWithHeaderImageRow, error) {
	rows, err := q.db.QueryContext(ctx, getSectionsWithHeaderImage, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSectionsWithHeaderImageRow
	for rows.Next() {
		var i GetSectionsWithHeaderImageRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.Name,
			&i.Description,
			&i.Path,
			&i.LayoutID,
			&i.LayoutName,
			&i.HeroTitleDark,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeaderImagePath,
			&i.HeaderImageAlt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :one
UPDATE section SET
    name = ?,
    description = ?,
    path = ?,
    layout_id = ?,
    layout_name = ?,
    hero_title_dark = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, name, description, path, layout_id, layout_name, hero_title_dark, created_by, updated_by, created_at, updated_at
`

type UpdateSectionParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Path          sql.NullString `json:"path"`
	LayoutID      sql.NullString `json:"layout_id"`
	LayoutName    sql.NullString `json:"layout_name"`
	HeroTitleDark sql.NullInt64  `json:"hero_title_dark"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, updateSection,
		arg.Name,
		arg.Description,
		arg.Path,
		arg.LayoutID,
		arg.LayoutName,
		arg.HeroTitleDark,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.LayoutID,
		&i.LayoutName,
		&i.HeroTitleDark,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
