// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSetting = `-- name: CreateSetting :one
INSERT INTO setting (id, site_id, short_id, name, description, value, ref_key, category, position, system, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at, category, position
`

type CreateSettingParams struct {
	ID          string         `json:"id"`
	SiteID      string         `json:"site_id"`
	ShortID     sql.NullString `json:"short_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Value       sql.NullString `json:"value"`
	RefKey      sql.NullString `json:"ref_key"`
	Category    sql.NullString `json:"category"`
	Position    sql.NullInt64  `json:"position"`
	System      sql.NullInt64  `json:"system"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, createSetting,
		arg.ID,
		arg.SiteID,
		arg.ShortID,
		arg.Name,
		arg.Description,
		arg.Value,
		arg.RefKey,
		arg.Category,
		arg.Position,
		arg.System,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Position,
	)
	return i, err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM setting WHERE id = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, id)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at, category, position FROM setting WHERE id = ?
`

func (q *Queries) GetSetting(ctx context.Context, id string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, id)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Position,
	)
	return i, err
}

const getSettingByName = `-- name: GetSettingByName :one
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at, category, position FROM setting WHERE site_id = ? AND name = ?
`

type GetSettingByNameParams struct {
	SiteID string `json:"site_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetSettingByName(ctx context.Context, arg GetSettingByNameParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByName, arg.SiteID, arg.Name)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Position,
	)
	return i, err
}

const getSettingByRefKey = `-- name: GetSettingByRefKey :one
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at, category, position FROM setting WHERE site_id = ? AND ref_key = ?
`

type GetSettingByRefKeyParams struct {
	SiteID string         `json:"site_id"`
	RefKey sql.NullString `json:"ref_key"`
}

func (q *Queries) GetSettingByRefKey(ctx context.Context, arg GetSettingByRefKeyParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByRefKey, arg.SiteID, arg.RefKey)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Position,
	)
	return i, err
}

const getSettingsBySiteID = `-- name: GetSettingsBySiteID :many
SELECT id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at, category, position FROM setting WHERE site_id = ? ORDER BY category, position, name
`

func (q *Queries) GetSettingsBySiteID(ctx context.Context, siteID string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, getSettingsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ShortID,
			&i.Name,
			&i.Description,
			&i.Value,
			&i.RefKey,
			&i.System,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :one
UPDATE setting SET
    name = ?,
    description = ?,
    value = ?,
    ref_key = ?,
    category = ?,
    position = ?,
    system = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, site_id, short_id, name, description, value, ref_key, system, created_by, updated_by, created_at, updated_at, category, position
`

type UpdateSettingParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Value       sql.NullString `json:"value"`
	RefKey      sql.NullString `json:"ref_key"`
	Category    sql.NullString `json:"category"`
	Position    sql.NullInt64  `json:"position"`
	System      sql.NullInt64  `json:"system"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSetting,
		arg.Name,
		arg.Description,
		arg.Value,
		arg.RefKey,
		arg.Category,
		arg.Position,
		arg.System,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ShortID,
		&i.Name,
		&i.Description,
		&i.Value,
		&i.RefKey,
		&i.System,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Position,
	)
	return i, err
}
