// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSite = `-- name: CreateSite :one
INSERT INTO site (id, short_id, name, slug, active, created_by, updated_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, short_id, name, slug, active, default_layout_id, default_layout_name, created_by, updated_by, created_at, updated_at
`

type CreateSiteParams struct {
	ID        string    `json:"id"`
	ShortID   string    `json:"short_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Active    int64     `json:"active"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite,
		arg.ID,
		arg.ShortID,
		arg.Name,
		arg.Slug,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.DefaultLayoutID,
		&i.DefaultLayoutName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM site WHERE id = ?
`

func (q *Queries) DeleteSite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSite, id)
	return err
}

const getSite = `-- name: GetSite :one
SELECT id, short_id, name, slug, active, default_layout_id, default_layout_name, created_by, updated_by, created_at, updated_at FROM site WHERE id = ?
`

func (q *Queries) GetSite(ctx context.Context, id string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.DefaultLayoutID,
		&i.DefaultLayoutName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, short_id, name, slug, active, default_layout_id, default_layout_name, created_by, updated_by, created_at, updated_at FROM site WHERE slug = ?
`

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteBySlug, slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.DefaultLayoutID,
		&i.DefaultLayoutName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSites = `-- name: ListAllSites :many
SELECT id, short_id, name, slug, active, default_layout_id, default_layout_name, created_by, updated_by, created_at, updated_at FROM site ORDER BY name
`

func (q *Queries) ListAllSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listAllSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.Name,
			&i.Slug,
			&i.Active,
			&i.DefaultLayoutID,
			&i.DefaultLayoutName,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, short_id, name, slug, active, default_layout_id, default_layout_name, created_by, updated_by, created_at, updated_at FROM site WHERE active = 1 ORDER BY name
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.Name,
			&i.Slug,
			&i.Active,
			&i.DefaultLayoutID,
			&i.DefaultLayoutName,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE site SET
    name = ?,
    slug = ?,
    active = ?,
    default_layout_id = ?,
    default_layout_name = ?,
    updated_by = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, short_id, name, slug, active, default_layout_id, default_layout_name, created_by, updated_by, created_at, updated_at
`

type UpdateSiteParams struct {
	Name              string         `json:"name"`
	Slug              string         `json:"slug"`
	Active            int64          `json:"active"`
	DefaultLayoutID   sql.NullString `json:"default_layout_id"`
	DefaultLayoutName sql.NullString `json:"default_layout_name"`
	UpdatedBy         string         `json:"updated_by"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, updateSite,
		arg.Name,
		arg.Slug,
		arg.Active,
		arg.DefaultLayoutID,
		arg.DefaultLayoutName,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.DefaultLayoutID,
		&i.DefaultLayoutName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
